"""
--- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...
If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...
Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....
You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2
This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..
So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?
"""

from dataclasses import dataclass
from enum import Enum
from typing import Iterator, List, Optional

from . import challenge, Path


class Direction(Enum):
    UP = "U"
    DOWN = "D"
    RIGHT = "R"
    LEFT = "L"


@dataclass(frozen=True, slots=True)
class Position:
    row: int
    col: int

    def move(self, direction: Direction) -> "Position":
        match direction:
            case Direction.UP:
                return Position(row=self.row + 1, col=self.col)
            case Direction.DOWN:
                return Position(row=self.row - 1, col=self.col)
            case Direction.LEFT:
                return Position(row=self.row, col=self.col - 1)
            case Direction.RIGHT:
                return Position(row=self.row, col=self.col + 1)


@dataclass(frozen=True, slots=True)
class Move:
    direction: Direction
    distance: int

    def __str__(self):
        return f"{self.direction.value} {self.distance}"


class RopeState:
    def __init__(self, start_position: Optional[Position] = None):
        if start_position is None:
            start_position = Position(0, 0)
        self.start_position = start_position
        self.tail_position: Position = start_position
        self.head_position: Position = start_position
        self.tail_history: List[Position] = [start_position]
        self.head_history: List[Position] = [start_position]

    def move(self, direction: Direction):
        self.head_position = self.head_position.move(direction)
        self.head_history.append(self.head_position)
        row_delta = self.head_position.row - self.tail_position.row
        col_delta = self.head_position.col - self.tail_position.col
        # print(row_delta, col_delta)
        if abs(row_delta) > 1 or abs(col_delta) > 1:
            # we need to move the tail
            if row_delta > 0:
                row_delta = min(1, row_delta)
            elif row_delta < 0:
                row_delta = max(-1, row_delta)
            if col_delta > 0:
                col_delta = min(1, col_delta)
            elif col_delta < 0:
                col_delta = max(-1, col_delta)
            self.tail_position = Position(
                row=self.tail_position.row + row_delta, col=self.tail_position.col + col_delta
            )
            self.tail_history.append(self.tail_position)

    def apply(self, move: Move):
        for _ in range(move.distance):
            self.move(move.direction)
            # print(str(self))

    def __str__(self):
        history_cols = [
            p.col for p in self.tail_history + self.head_history
        ]
        history_rows = [
            p.row for p in self.tail_history + self.head_history
        ]
        min_col = min(self.head_position.col, self.tail_position.col, self.start_position.col, 0, *history_cols)
        min_row = min(self.head_position.row, self.tail_position.row, self.start_position.row, 0, *history_rows)
        max_col = max(self.head_position.col, self.tail_position.col, self.start_position.col, *history_cols)
        max_row = max(self.head_position.row, self.head_position.row, self.start_position.row, *history_rows)
        s: List[str] = []
        for row in range(max_row, min_row - 1, -1):
            for col in range(min_col, max_col + 1):
                match Position(row=row, col=col):
                    case self.head_position:
                        s.append("H")
                    case self.tail_position:
                        s.append("T")
                    case self.start_position:
                        s.append("s")
                    case _:
                        s.append(".")
            s.append("\n")
        return "".join(s)


def load(path: Path) -> Iterator[Move]:
    with open(path, "r") as f:
        for line in f:
            raw_direction, raw_distance = line.split()
            for direction in Direction:
                if direction.value == raw_direction:
                    break
            else:
                raise ValueError(f"Invalid direction: {raw_direction!r}")
            distance = int(raw_distance)
            yield Move(direction=direction, distance=distance)


@challenge(day=9)
def rope_positions(path: Path) -> int:
    state = RopeState()
    # print(str(state))
    for move in load(path):
        state.apply(move)
        # print(str(state))
    # print(state.tail_history)
    return len(frozenset(state.tail_history))
